#!/bin/sh
# create manifest of files in directory
# $1 -> title variable
title=$1
echo	"MANIFEST of package $title"				>	/tmp/$$
echo	'-----------------------------------'			>>	/tmp/$$
find . -type f -print | grep -v Config | sed -e 's|^\./||'	>>	/tmp/$$
echo	'-----------------------------------'			>>	/tmp/$$
mv	/tmp/$$	MANIFEST

#find . -print | grep -v '^\.$$' | grep -v configInfo	>	/tmp/$$.1
#sed -e 's/\.\///' < /tmp/$$.1				>	/tmp/$$.2
#grep -v tclConfig < /tmp/$$.2				>	/tmp/$$.1
#grep -v config.status	< /tmp/$$.1			>	/tmp/$$.2
#grep -v Makefile	< /tmp/$$.2			>	/tmp/$$.1
#grep -v PREPARE		< /tmp/$$.1			>>	/tmp/$$
#rm	/tmp/$$.*
